### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by nigun** [arenadata/db#1020]
Description:    Ubuntu 22.04.4 LTS

i have step by step README.linux.md

Then running  ./configure  and I get an error:

checking whether to build with LDAP support... no
checking whether to build with Bonjour support... no
checking whether to build with OpenSSL support... no
checking whether to build with SELinux support... no
configure: error: libxml is required by gpcloud

**Comment by KnightMurloc** [comment]
Use the commands to compile from the README. https://github.com/arenadata/gpdb/blob/adb-6.x/README.md#build-the-database

**Comment by nigun** [comment]
Hi.
that's what I did too
 
run
make -j8
i have error
 
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h:837:22: error: ‘XMLCh’ does not name a type
  837 |         static const XMLCh *XmlstrToken(Edxltoken token_type);
      |                      ^~~~~
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h: In constructor ‘gpdxl::CDXLTokens::SXMLStrMapElem::SXMLStrMapElem()’:
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h:799:64: error: class ‘gpdxl::CDXLTokens::SXMLStrMapElem’ does not have any field named ‘m_xmlsz’
  799 |                 SXMLStrMapElem() : m_edxlt(EdxltokenSentinel), m_xmlsz(NULL)
      |                                                                ^~~~~~~
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h: In constructor ‘gpdxl::CDXLTokens::SXMLStrMapElem::SXMLStrMapElem(gpdxl::Edxltoken, int*)’:
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h:805:43: error: class ‘gpdxl::CDXLTokens::SXMLStrMapElem’ does not have any field named ‘m_xmlsz’
  805 |                         : m_edxlt(edxlt), m_xmlsz(xml_val)
      |                                           ^~~~~~~
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h: In destructor ‘gpdxl::CDXLTokens::SXMLStrMapElem::~SXMLStrMapElem()’:
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h:814:68: error: ‘m_xmlsz’ was not declared in this scope; did you mean ‘m_pxmlszmap’?
  814 |                         GPOS_DELETE_ARRAY(reinterpret_cast<BYTE *>(m_xmlsz));
      |                                                                    ^~~~~~~
      |                                                                    m_pxmlszmap
make[6]: *** [<builtin>: CMDAccessor.o] Error 1
make[6]: *** Waiting for unfinished jobs....
In file included from CMDKey.cpp:16:
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/CDXLUtils.h: At global scope:
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/CDXLUtils.h:226:58: error: ‘XMLCh’ does not name a type
  226 |                 CDXLMemoryManager *memory_manager, const XMLCh *);
      |                                                          ^~~~~
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/CDXLUtils.h:230:89: error: ‘XMLCh’ does not name a type
  230 |                                                                                   const XMLCh *xml_string,
      |                                                                                         ^~~~~
../../../../../../src/backend/gporca/libnaucrates/include/naucrates/dxl/CDXLUtils.h:242:95: error: ‘XMLCh’ does not name a type
  242 |                                                                                         const XMLCh *xml_string);
      |                                                                                               ^~~~~
make[6]: *** [<builtin>: CMDKey.o] Error 1
make[6]: Leaving directory '/home/a3admin/gpdb_src/src/backend/gporca/libgpopt/src/mdcache'
make[5]: *** [../../../../../src/backend/common.mk:41: mdcache-recursive] Error 2
make[5]: Leaving directory '/home/a3admin/gpdb_src/src/backend/gporca/libgpopt/src'
make[4]: *** [../../../../src/backend/common.mk:41: src-recursive] Error 2
make[4]: Leaving directory '/home/a3admin/gpdb_src/src/backend/gporca/libgpopt'
make[3]: *** [../../../src/backend/common.mk:41: libgpopt-recursive] Error 2
make[3]: Leaving directory '/home/a3admin/gpdb_src/src/backend/gporca'
make[2]: *** [common.mk:41: gporca-recursive] Error 2
make[2]: Leaving directory '/home/a3admin/gpdb_src/src/backend'
make[1]: *** [Makefile:34: all-backend-recurse] Error 2
make[1]: Leaving directory '/home/a3admin/gpdb_src/src'
make: *** [GNUmakefile:12: all-src-recurse] Error 2
 
 
 
  
>Пятница, 23 августа 2024, 11:08 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>Use the commands to compile from the README.  https://github.com/arenadata/gpdb/blob/adb-6.x/README.md#build-the-database
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2306532796 @ github . com> 
 
 
--
Николай Пелипец

**Comment by KnightMurloc** [comment]
It looks like you're using xerces 3.2 from the repository. The build with this version for 6X is not supported. Use the version from the fork https://github.com/arenadata/gp-xerces

**Comment by nigun** [comment]
I  download xerces
../configure --prefix=/usr/local
make
make install
 
run  
make -j8
 
and i have  error:
 

 
/usr/bin/ld: CDXLUtils.cpp:(.text+0x2995): undefined reference to `xercesc_3_1::XMLUni::fgXercesSchemaExternalSchemaLocation'
/usr/bin/ld: gporca/libnaucrates/src/CDXLUtils.o: in function `gpdxl::CDXLUtils::CreateStringFrom64XMLStr(gpdxl::CDXLMemoryManager*, unsigned short const*, u                                   nsigned int*)':
CDXLUtils.cpp:(.text+0x2d40): undefined reference to `xercesc_3_1::Base64::decode(unsigned char const*, unsigned long*, xercesc_3_1::MemoryManager*, xercesc_                                   3_1::Base64::Conformance)'
/usr/bin/ld: gporca/libnaucrates/src/CDXLUtils.o: in function `gpdxl::CDXLUtils::EncodeByteArrayToString(gpos::CMemoryPool*, unsigned char const*, unsigned i                                   nt)':
CDXLUtils.cpp:(.text+0x2f22): undefined reference to `xercesc_3_1::Base64::encode(unsigned char const*, unsigned long, unsigned long*, xercesc_3_1::MemoryMan                                   ager*)'
/usr/bin/ld: gporca/libnaucrates/src/CDXLUtils.o: in function `gpdxl::CDXLUtils::DecodeByteArrayFromString(gpos::CMemoryPool*, gpos::CWStringDynamic const*,                                    unsigned int*)':
CDXLUtils.cpp:(.text+0x31c6): undefined reference to `xercesc_3_1::Base64::decode(unsigned char const*, unsigned long*, xercesc_3_1::MemoryManager*, xercesc_                                   3_1::Base64::Conformance)'
/usr/bin/ld: gporca/libnaucrates/src/CDXLUtils.o: in function `gpdxl::CDXLUtils::CreateDynamicStringFromXMLChArray(gpdxl::CDXLMemoryManager*, unsigned short                                    const*)':
CDXLUtils.cpp:(.text+0x32e7): undefined reference to `xercesc_3_1::XMLString::transcode(unsigned short const*, xercesc_3_1::MemoryManager*)'
/usr/bin/ld: CDXLUtils.cpp:(.text+0x333a): undefined reference to `xercesc_3_1::XMLString::release(char**, xercesc_3_1::MemoryManager*)'
/usr/bin/ld: gporca/libnaucrates/src/CDXLUtils.o: in function `gpdxl::CDXLUtils::GetParseHandlerForDXLString(gpos::CMemoryPool*, char const*, char const*) [c                                   lone .cold]':
CDXLUtils.cpp:(.text.unlikely+0x1e6): undefined reference to `xercesc_3_1::XMemory::operator delete(void*, xercesc_3_1::MemoryManager*)'
/usr/bin/ld: gporca/libnaucrates/src/CDXLUtils.o:(.data.rel.local.DW.ref._ZTIN11xercesc_3_112XMLExceptionE[DW.ref._ZTIN11xercesc_3_112XMLExceptionE]+0x0): un                                   defined reference to `typeinfo for xercesc_3_1::XMLException'
/usr/bin/ld: gporca/libnaucrates/src/CDXLUtils.o:(.data.rel.local.DW.ref._ZTIN11xercesc_3_117SAXParseExceptionE[DW.ref._ZTIN11xercesc_3_117SAXParseExceptionE                                   ]+0x0): undefined reference to `typeinfo for xercesc_3_1::SAXParseException'
/usr/bin/ld: gporca/libnaucrates/src/init.o: in function `InitDXL':
init.cpp:(.text+0x61): undefined reference to `xercesc_3_1::XMLUni::fgXercescDefaultLocale'
/usr/bin/ld: init.cpp:(.text+0x66): undefined reference to `xercesc_3_1::XMLPlatformUtils::Initialize(char const*, char const*, xercesc_3_1::PanicHandler*, x                                   ercesc_3_1::MemoryManager*)'
/usr/bin/ld: gporca/libnaucrates/src/init.o: in function `ShutdownDXL':
init.cpp:(.text+0xc6): undefined reference to `xercesc_3_1::XMLPlatformUtils::Terminate()'
/usr/bin/ld: gporca/libnaucrates/src/parser/CParseHandlerDefaultValueExpr.o: in function `gpdxl::CParseHandlerDefaultValueExpr::EndElement(unsigned short con                                   st*, unsigned short const*, unsigned short const*)':
CParseHandlerDefaultValueExpr.cpp:(.text+0x22): undefined reference to `xercesc_3_1::XMLString::compareString(unsigned short const*, unsigned short const*)'
/usr/bin/ld: gporca/libnaucrates/src/parser/CParseHandlerDefaultValueExpr.o: in function `gpdxl::CParseHandlerDefaultValueExpr::StartElement(unsigned short c                                   onst*, unsigned short const*, unsigned short const*, xercesc_3_1::Attributes const&)':
CParseHandlerDefaultValueExpr.cpp:(.text+0xe6): undefined reference to `xercesc_3_1::XMLString::compareString(unsigned short const*, unsigned short const*)'
/usr/bin/ld: gporca/libnaucrates/src/parser/CParseHandlerDummy.o: in function `gpdxl::CParseHandlerDummy::error(xercesc_3_1::SAXParseException const&)':
CParseHandlerDummy.cpp:(.text+0x25): undefined reference to `xercesc_3_1::XMLString::transcode(unsigned short const*, xercesc_3_1::MemoryManager*)'
/usr/bin/ld: gporca/libnaucrates/src/parser/CParseHandlerDummy.o: in function `non-virtual thunk to gpdxl::CParseHandlerDummy::error(xercesc_3_1::SAXParseExc                                   eption const&)':
CParseHandlerDummy.cpp:(.text+0x83): undefined reference to `xercesc_3_1::XMLString::transcode(unsigned short const*, xercesc_3_1::MemoryManager*)'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:68: postgres] Error 1
make[2]: Leaving directory '/home/a3admin/gpdb_src/src/backend'
make[1]: *** [Makefile:34: all-backend-recurse] Error 2
make[1]: Leaving directory '/home/a3admin/gpdb_src/src'
make: *** [GNUmakefile:12: all-src-recurse] Error 2
***@***.***:/home/a3admin/gpdb_src# make -j8
 
 
  
>Пятница, 23 августа 2024, 12:11 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>It looks like you're using xerces 3.2 from the repository. The build with this version for 6X is not supported. Use the version from the fork  https://github.com/arenadata/gp-xerces
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2306652453 @ github . com> 
 
 
--
Николай Пелипец

**Comment by KnightMurloc** [comment]
Have you deleted the library version from the repository? Having two versions in the system leads to build errors.

**Comment by nigun** [comment]
Ты про gp-xerces 6 версии?

  
>Пятница, 23 августа 2024, 13:44 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>Have you deleted the library version from the repository? Having two versions in the system leads to build errors.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2306821604 @ github . com> 
 
 
--
Николай Пелипец

**Comment by KnightMurloc** [comment]
Для сборки gpdb 6 нужен gp-xerces. наличие xerces из репазитория в системе может сломать сбору.

**Comment by nigun** [comment]
Спасибо. Я уже. Столько накрутил там .... В общем в понедельник снесу виртуалку и сделаю все с нуля. Я сам н и разу не девопрс, порой туго соображаю в никсах
--
Отправлено из Mail.ru для Android пятница, 23 августа 2024г., 16:22 +03:00 от Viktor Kurilko  ***@***.*** :

**Comment by nigun** [comment]
Привет.
Дошел до шага
make create-demo-cluster
Запускал из дириктории  где исходники:  gpdb_src
 
получил набор ошибок:
 
    from gppylib.commands.unix import Hostname, Echo
  File "/usr/local/gpdb/lib/python/gppylib/commands/unix.py", line 10, in <module>
    import psutil
ImportError: No module named psutil
Traceback (most recent call last):
  File "/usr/local/gpdb/bin/gpssh", line 32, in <module>
    from gppylib.util import ssh_utils
  File "/usr/local/gpdb/lib/python/gppylib/util/ssh_utils.py", line 13, in <module>
    from gppylib.commands.unix import Hostname, Echo
  File "/usr/local/gpdb/lib/python/gppylib/commands/unix.py", line 10, in <module>
    import psutil
ImportError: No module named psutil
grep: clusterConfigPostgresAddonsFile: No such file or directory
 
======================================================================
CLUSTER_CONFIG_POSTGRES_ADDONS: clusterConfigPostgresAddonsFile
----------------------------------------------------------------------
fsync=off
======================================================================
 
==========================================================================================
executing:
  /usr/local/gpdb/bin/gpinitsystem -a -c clusterConfigFile  -l /home/a3admin/gpdb_src/gpAux/gpdemo/datadirs/gpAdminLogs -p clusterConfigPostgresAddonsFile -s m9-it-greenplum-01 -P 6001 -S /home/a3admin/gpdb_src/gpAux/gpdemo/datadirs/standby ""
==========================================================================================
 
20240826:13:41:36:037402 gpinitsystem:m9-it-greenplum-01:root-[INFO]:-Checking configuration parameters, please wait...
20240826:13:41:36:037402 gpinitsystem:m9-it-greenplum-01:root-[FATAL]:-Unable to run this script as root Script Exiting!
========================================
gpinitsystem returned: 2
========================================
 
======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. : psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.6000"?
======================================================================
 
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.6000"?
======================================================================
 
make[1]: *** [Makefile:45: create-demo-cluster] Error 2
make[1]: Leaving directory '/home/a3admin/gpdb_src/gpAux/gpdemo'
make: *** [GNUmakefile:158: create-demo-cluster] Error 2
 
 
  
>Пятница, 23 августа 2024, 16:22 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>Для сборки gpdb 6 нужен gp-xerces. наличие xerces из репазитория в системе может сломать сбору.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2307086611 @ github . com> 
 
 
--
Николай Пелипец

**Comment by nigun** [comment]
В догонку
сделал так, не знаю корректно или нет:
 
sudo apt update
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
sudo python2 get-pip.py
 
pip install psutil
 
  
>Пятница, 23 августа 2024, 16:22 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>Для сборки gpdb 6 нужен gp-xerces. наличие xerces из репазитория в системе может сломать сбору.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2307086611 @ github . com> 
 
 
--
Николай Пелипец

**Comment by nigun** [comment]
Привет. Продолжаю мучать.
 После установки pip и psutil, стал запускаться make create-demo-CLUSTER. Требует пороль от рута и не  принимает его.
 Пересообрал под другим пользователем с рутовыми парвами. Запустил. На выходе имеею вот такую ошибку:
 
 20240826:15:43:12:074667 gpinitsystem:m9-it-greenplum-01:a3admin-[INFO]:-Checking new segment hosts, please wait...
./bin/touch: cannot touch '/home/a3admin/gpdb_src/gpAux/gpdemo/datadirs/dbfast1/tmp_file_test': No such file or directory
20240826:15:43:12:074667 gpinitsystem:m9-it-greenplum-01:a3admin-[FATAL]:-Cannot write to /home/a3admin/gpdb_src/gpAux/gpdemo/datadirs/dbfast1 on m9-it-greenplum-01  Script Exiting!
========================================
gpinitsystem returned: 2
========================================
 
======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. : psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.6000"?
======================================================================
 
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.6000"?
======================================================================
 
make[1]: *** [Makefile:45: create-demo-cluster] Error 2
make[1]: Leaving directory '/home/a3admin/gpdb_src/gpAux/gpdemo'
make: *** [GNUmakefile:158: create-demo-cluster] Error 2
 
 
 
Заранее спасибо.
>Пятница, 23 августа 2024, 16:22 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>Для сборки gpdb 6 нужен gp-xerces. наличие xerces из репазитория в системе может сломать сбору.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2307086611 @ github . com> 
 
 
--
Николай Пелипец

**Comment by KnightMurloc** [comment]
1. запускать нужно от любого не root пользователя. 2. для этого пользователя должен быть настроен без парольный вход по ssh. 3. по поводу директорий проверяй что пользователь имеет к ним доступ.

**Comment by nigun** [comment]
Думаю почти разобрался но не факт.
Остановился вот а этом:

  
>Вторник, 27 августа 2024, 10:52 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>*  запускать нужно от любого не root пользователя. 2. для этого пользователя должен быть настроен без парольный вход по ssh. 3. по поводу директорий проверяй что пользователь имеет к ним доступ.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2311811926 @ github . com> 
 
 
--
Николай Пелипец

**Comment by nigun** [comment]
Ну и осталось понять  всю эту петрушку

 
6 постгресов :)
  
>Вторник, 27 августа 2024, 10:52 +03:00 от Viktor Kurilko ***@***.***>:
> 
> 
>*  запускать нужно от любого не root пользователя. 2. для этого пользователя должен быть настроен без парольный вход по ssh. 3. по поводу директорий проверяй что пользователь имеет к ним доступ.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <arenadata/gpdb/issues/1020/2311811926 @ github . com> 
 
 
--
Николай Пелипец

**Comment by nigun** [comment]
Отвлечённый вопрос. Я как понимаю вы один из разработчиков этой ветки?
--
Отправлено из Mail.ru для Android вторник, 27 августа 2024г., 10:52 +03:00 от Viktor Kurilko  ***@***.*** :
